services:
  esport.web:
    image: esport.web
    build:
      context: .
      dockerfile: Esport.Web/Dockerfile

  esport.client:
    image: esport.client
    build:
      context: .
      dockerfile: Esport.Client/Dockerfile
