services:
  esport.web:
    image: esport.web
    build:
      context: .
      dockerfile: Esport.Web/Dockerfile

  esport.kafka.subscriber:
    image: esport.kafka.subscriber
    build:
      context: .
      dockerfile: Esport.Kafka.Subscriber/Dockerfile

  esport.generator.service:
    image: esport.generator.service
    build:
      context: .
      dockerfile: Esport.Generator.Service/Dockerfile